### ISSUE TITLE
Add a webhook by setting up a basic CI/CD process using Travis CI and AWS

### ISSUE THREAD

**Issue by GoodSergiy** [GoodSergiy/homepage#24]

**Comment by GoodSergiy** [comment]
При регистрации требует ввести номер кредитной или дебетовой карты. 
```Для подтверждения личности введите свою платежную информацию.```
С этим есть определённые проблемы на физическом уровне, к сожалению не смогу выполнить этот пункт :(

**Comment by dasha-korotkykh** [comment]
That's okay, skip it

**Comment by GoodSergiy** [comment]
> That's okay, skip it

Ok. Then I leave it like it is now. Have sent home task for a final review at my study.binary-studio account.
