### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by GoodSergiy** [GoodSergiy/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dasha-korotkykh** [comment]
I would be glad to help you with reviewing this block if you have any doubts, just go ahead and put together what you would like to tell about yourself in your personal resume.

**Comment by GoodSergiy** [comment]
> I would be glad to help you with reviewing this block if you have any doubts, just go ahead and put together what you would like to tell about yourself in your personal resume.

Ok, for now I have just put a "Lorem Ipsum" information in order to close this and other issues, will correct it after finishing the entire lecture.
